import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { FactRow } from '../build/db';
import { type ArthaIndex, openArthaIndex } from '../mcp/query';

// Static (no timestamp) so re-exports of unchanged input are byte-identical —
// minimal git diffs (T09 acceptance: deterministic output).
const BANNER = `<!-- Generated by \`artha export --agents-md\`. DO NOT EDIT — your changes will be overwritten.
     Source of truth: .artha/ (certified entries only). Regenerate with \`artha export --agents-md\`. -->`;

const TITLE = '# Product meaning (certified)';
const INTRO =
  '> Certified decisions, invariants, and conventions for this codebase — generated by Artha from `.artha/`.';

// Keep the artifact terse: an invariant scoped to a broad glob can expand to many
// files in the index; list a handful, then summarize the rest.
const SCOPE_CAP = 8;

/**
 * Render a compact, deterministic `AGENTS.md` of **certified** entries grouped by
 * kind. Proposed/stale are excluded by definition. Reads from the built index
 * (T08 `query.ts` read layer) — chosen over re-reading YAML so export reflects
 * the same validated, staleness-resolved state the MCP server serves.
 */
export function renderAgentsMd(index: ArthaIndex): string {
  const certified = index.facts.filter((fact) => fact.status === 'certified');
  const header = `${BANNER}\n\n${TITLE}\n`;

  if (certified.length === 0) {
    return `${header}\n_No certified entries yet. Mine with \`artha mine\`, certify with \`artha review\`, build with \`artha build\`, then re-export._\n`;
  }

  const pinsByFact = groupValues(
    index.pins,
    (p) => p.fact_id,
    (p) => p.symbol_ref,
  );
  const scopeByFact = groupValues(
    index.scopeFiles,
    (s) => s.fact_id,
    (s) => s.file_path,
  );

  const sections: string[] = [];
  const decisions = certified.filter((f) => f.kind === 'decision');
  const invariants = certified.filter((f) => f.kind === 'invariant');
  const conventions = certified.filter((f) => f.kind === 'convention');

  if (decisions.length > 0) {
    sections.push(section('Decisions', decisions, (f) => renderDecision(f, pinsByFact)));
  }
  if (invariants.length > 0) {
    sections.push(
      section('Invariants', invariants, (f) => renderRule(f, pinsByFact, scopeByFact, true)),
    );
  }
  if (conventions.length > 0) {
    sections.push(
      section('Conventions', conventions, (f) => renderRule(f, pinsByFact, scopeByFact, false)),
    );
  }

  return `${header}\n${INTRO}\n\n${sections.join('\n')}`;
}

export interface ExportResult {
  outPath: string;
  /** Number of certified entries written. */
  certified: number;
  /** False when there was no built index (or it was empty) — caller may hint `artha build`. */
  hadIndex: boolean;
}

/**
 * Render and write `AGENTS.md` for `repoRoot`. Default output is `AGENTS.md` at
 * the repo root; override with `out`. Fully offline; never throws on a missing
 * index (writes the empty-state file instead).
 */
export function exportAgentsMd(repoRoot: string, options: { out?: string } = {}): ExportResult {
  const dbPath = join(repoRoot, '.artha', 'index.db');
  const outPath = options.out ?? join(repoRoot, 'AGENTS.md');
  const index = openArthaIndex(dbPath);
  try {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, renderAgentsMd(index), 'utf8');
    return {
      outPath,
      certified: index.facts.filter((fact) => fact.status === 'certified').length,
      hadIndex: !index.empty,
    };
  } finally {
    index.close();
  }
}

function section(name: string, facts: FactRow[], render: (fact: FactRow) => string): string {
  const entries = [...facts]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map(render)
    .join('\n\n');
  return `## ${name}\n\n${entries}\n`;
}

function renderDecision(fact: FactRow, pinsByFact: Map<string, string[]>): string {
  const lines = [heading(fact)];
  if (fact.body) lines.push(fact.body);
  addPins(lines, pinsByFact.get(fact.id));
  if (fact.supersedes) lines.push(`- supersedes: ${code(fact.supersedes)}`);
  return lines.join('\n');
}

function renderRule(
  fact: FactRow,
  pinsByFact: Map<string, string[]>,
  scopeByFact: Map<string, string[]>,
  isInvariant: boolean,
): string {
  const severity = isInvariant && fact.severity ? ` (severity: ${fact.severity})` : '';
  const lines = [`${heading(fact)}${severity}`];
  if (fact.body) lines.push(fact.body);
  if (isInvariant && fact.why) lines.push(`- why: ${code(fact.why)}`);
  addPins(lines, pinsByFact.get(fact.id));
  addScope(lines, scopeByFact.get(fact.id));
  return lines.join('\n');
}

function heading(fact: FactRow): string {
  return `### ${fact.id} — ${fact.heading ?? ''}`.trimEnd();
}

function addPins(lines: string[], refs: string[] | undefined): void {
  if (!refs || refs.length === 0) return;
  lines.push(`- pins: ${unique(refs).map(code).join(', ')}`);
}

function addScope(lines: string[], files: string[] | undefined): void {
  if (!files || files.length === 0) return;
  const all = unique(files);
  const shown = all.slice(0, SCOPE_CAP).map(code).join(', ');
  const extra = all.length > SCOPE_CAP ? ` (+${all.length - SCOPE_CAP} more)` : '';
  lines.push(`- scope: ${shown}${extra}`);
}

function unique(values: string[]): string[] {
  return [...new Set(values)].sort();
}

function code(value: string): string {
  return `\`${value}\``;
}

function groupValues<T>(
  rows: T[],
  key: (row: T) => string,
  value: (row: T) => string,
): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const row of rows) {
    const k = key(row);
    const bucket = map.get(k);
    if (bucket) bucket.push(value(row));
    else map.set(k, [value(row)]);
  }
  return map;
}
